create table if not exists movies (
  id bigint generated by default as identity primary key,
  title text not null,
  director text not null,
  year integer not null check (year >= 1888 and year <= 2100),
  genre text not null,
  rating numeric not null check (rating >= 0 and rating <= 10),
  duration time not null
);

alter table movies enable row level security;

drop policy if exists "Public movies select" on movies;
drop policy if exists "Public movies insert" on movies;
drop policy if exists "Public movies update" on movies;
drop policy if exists "Public movies delete" on movies;

create policy "Public movies select"
on movies for select
to anon
using (true);

create policy "Public movies insert"
on movies for insert
to anon
with check (true);

create policy "Public movies update"
on movies for update
to anon
using (true)
with check (true);

create policy "Public movies delete"
on movies for delete
to anon
using (true);

insert into movies (id, title, director, year, genre, rating, duration)
values
  (1, 'Inception', 'Christopher Nolan', 2010, 'Sci-fi', 8.8, '02:28'),
  (2, 'Forrest Gump', 'Robert Zemeckis', 1994, 'Drama', 8.8, '02:22'),
  (3, 'The Matrix', 'Lana Wachowski, Lilly Wachowski', 1999, 'Sci-fi', 8.7, '02:16')
on conflict (id) do nothing;

select setval('movies_id_seq', (select max(id) from movies));
